### ISSUE TITLE
[Linux]  builds (with some changes) but segmentation fault when loading .mtl files

### ISSUE THREAD

**Issue by ebachard** [peternmai/BumperCarSimulation#1]
After some little changes, I was able to compile ll the code under Linux (x86_64), using OpenGL 3.3 + glfw 3.2.

After I fixed several shader issues compilations, I can launch the binary, glew inits correctly, OpenGL 3.3 is loaded, all shaders seems to compile fine ... but once objects start loading,  I hit a strange segmentation fault caused by .mtl files (if I'm not mistaken).
The log says : 

```
 $ ./CarBump
Renderer: NVA5
OpenGL version supported 3.3 (Core Profile) Mesa 17.2.8
Supported GLSL version is 3.30.
Current GLEW version: 1.13.0
Compiling shader : ../Shaders/skyboxShader.vert
Successfully compiled vertex shader!
Compiling shader : ../Shaders/skyboxShader.frag
Successfully compiled fragment shader!
Linking program
Compiling shader : ../Shaders/geometryShader.vert
Successfully compiled vertex shader!
Compiling shader : ../Shaders/geometryShader.frag
Successfully compiled fragment shader!
Linking program
Compiling shader : ../Shaders/lineShader.vert
Successfully compiled vertex shader!
Compiling shader : ../Shaders/lineShader.frag
Successfully compiled fragment shader!
Linking program
Compiling shader : ../Shaders/boundingboxShader.vert
Successfully compiled vertex shader!
Compiling shader : ../Shaders/boundingboxShader.frag
Successfully compiled fragment shader!
Linking program
Compiling shader : ../Shaders/particles.vert
Successfully compiled vertex shader!
Compiling shader : ../Shaders/particles.frag
Successfully compiled fragment shader!
Linking program
Compiling shader : ../Shaders/shadowDepthMap.vert
Successfully compiled vertex shader!
Compiling shader : ../Shaders/shadowDepthMap.frag
Successfully compiled fragment shader!
Linking program
Compiling shader : ../Shaders/shadowFirstPass.vert
Successfully compiled vertex shader!
Compiling shader : ../Shaders/shadowFirstPass.frag
Successfully compiled fragment shader!
Linking program

Loading in: ../Objects/sphere.obj
Center Shifter: 4.76837e-07 0 0
Scale Factor:   0.993976
Erreur de segmentation

```

What does mean ".mtl" files ?  Is it Apple only ? Or is there a way to use that on Linux ?

Of course, I can provide the little shell script + a diff to help other Linux testers.

Last but not least, thanks a lot for sharing your (very) interesting code.

-- 
ericb

**Comment by peternmai** [comment]
Hmm.. interesting. We've tested this code on both MacOS and Windows, but haven't tried on a Linux environment. I might have an idea of where it's happening though.

The ".mtl" files describe the material (color, ambient/diffuse/specular coefficient, etc) of the object to be render. They are not particular to Apple devices.

From your output, it seems that you were successful in reading in the .mtl files. The object is centered and scaled to fit in a 2x2x2 box at the origin of the world only after reading in both the .obj and .mtl files. You can try to confirm this by adding `cout << "Successfully parsed " << verticesAttributes.size() << " attributes" << endl;` after `line (24): parse(filepath, boxSize)` in OBJObject.cpp.

Output should be: 

```
Loading in: ../Objects/sphere.obj
Center Shifter: 4.76837e-07 0 0
Scale Factor:   0.993976
Successfully parsed 1146 attributes
```

If this is the case, it'll lead me to believe that your program is seg-faulting when calling GLEW functions. There are three places this might happen:

- Line 41-69 of OBJObject.cpp: Storing sphere.obj's attributes onto the GPU
- Line 560-582 of Window.cpp: Initializing a texture map for shadow calculation on GPU
- Line 14-47 of Particles.cpp: Initializing particle attributes on the GPU

Note: Loading in sphere.obj is called on line 106 of Window.cpp. 

Hope this narrows it down somewhat

**Comment by ebachard** [comment]
Thanks a lot for your great explanation .

I followed your suggestion, and indeed, I got:

```
Loading in: ../Objects/sphere.obj
Center Shifter: 4.76837e-07 0 0
Scale Factor:   0.993976
Successfully parsed 1146 attributes

(then segfault) :-/
```
So, the problem is very probably on my side, and I'll check more precisely what is happening with glew.

FYI, on the GLEW side, here is what I have added a -DGL3_PROTOTYPES=1 , but maybe I should initialize glew using glewExperimental() = GL_TRUE + glewInit() somewhere (Linux unfortunaly needs such hacks).

Waiting, I have slightly modified Windows.cpp (see the diff below):

```

diff --git a/BumperCarSimulation/Window.cpp b/BumperCarSimulation/Window.cpp
index e6609bb..1ec8816 100644
--- a/BumperCarSimulation/Window.cpp
+++ b/BumperCarSimulation/Window.cpp
@@ -202,7 +202,7 @@ GLFWwindow* Window::create_window(int width, int height)
     // 16x antialiasing
     glfwWindowHint(GLFW_SAMPLES, 16);
     
-    #ifdef __APPLE__ // Because Apple hates comforming to standards
+    #if defined( __APPLE__) || defined (Linux) // Because Apple hates comforming to standards
     // Ensure that minimum OpenGL version is 3.3
     glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
     glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
```

I'll continue to search, and of course, I can't make it work, I will propose a Makefile for Linux or some build script to share my changes.  Thanks again for your fast and precise answer !

**Comment by ebachard** [comment]
I forgot, using glew2.1.0 instead of 1.13 (from today's github pull), there is some progress:

```
Loading in: ../Objects/sphere.obj
Center Shifter: 4.76837e-07 0 0
Scale Factor:   0.993976
Successfully parsed 1146 attributes

Loading in: ../Objects/Blimp.obj
Center Shifter: 0.314508 -0.537765 -0.437979
Scale Factor:   0.2764
Successfully parsed 9042 attributes

Loading in: ../Objects/Car1.obj
Unable to read: ../Objects/Car1.obj
Deallocating memory for particles...
Deallocating memory for ../Objects/sphere.obj from GPU... Successful
```

Car1.obj seems to not be loadable, but maybe it's because I'm using a free driver (no GPU on my Macbook pro 6,2  + running Linux)

(to be continued)

**Comment by ebachard** [comment]
Haha, got it working !

The issue was  an UPPER/LOWER case error in the names of object files in Windows.hpp 
( s/Car1.obj/car1.obj/  and elsewhere, s/Car1.mtl/car1.mtl) et voilà (not suprised it works on Windows though  :-) )

**Comment by ebachard** [comment]
PR created. Build is ok, and BTW, I fixed some little warnings  ;-)

Do what you want with the proposed PR.

Issue really closed now.
